server:
  port: 9000
  base-url: http://localhost:9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thesis_test?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis:
#  type-aliases-package: com.example.newDemo.bean
file:
  upload-dir-avatar: E:/1/thesis_test/village_test/uploads/avatars
  upload-dir-moment: E:/1/thesis_test/village_test/uploads/momentpics
  upload-dir-question: E:/1/thesis_test/village_test/uploads/aqfiles
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.thesis.village.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: assign_id
      update-strategy: not_null

snowflake:
  data-center-id: 1 # 数据中心ID，可以使用机器IP地址最后一段数字，范围为0-31
  machine-id: 1 # 机器ID，可以使用服务器编号，范围为0-31
  
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  
ai:
  moonshot:
    api-key: sk-psGCcZ3ndv8WUPfNqMx69eFxSPiA6WcFVfz7gVChMofc0ZM4